services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_USERNAME}
    ports:
      - "5432:5432"
    volumes:
      - scottabbey.com-data:/var/lib/postgresql/data:rw

volumes:
  scottabbey.com-data:
