services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: bastiondev
      POSTGRES_PASSWORD: UhTp9783
      POSTGRES_DB: bastiondev
    volumes:
      - db:/var/lib/postgresql/data:rw

volumes:
  db:
