version: '3.4'

services:
  website:
    image: website
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3333:3333
