services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data:rw

volumes:
  db:
