name: Build
on:
  push:
    branches:
      - main
  pull_request:

env:
  IMAGE_NAME: bastion-be
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout [main]
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install
      - name: Build affected
        run: npx nx affected --target=build --parallel=3
      - name: Test affected
        run: npx nx affected --target=test --parallel=2
      - name: Log into Github Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Create Docker images
        run: npx nx affected --target=docker --parallel=3
      - name: Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly
        run: flyctl deploy --remote-only
